### ISSUE TITLE
Investigate path issue on Windows for save request

### ISSUE THREAD

**Issue by ndoschek** [eclipse-emfcloud/emfcloud-modelserver#173]
Currently, the save request that uses the modelUri path as parameter stopped working on Windows.
See also the discussion https://github.com/eclipse-emfcloud/emfcloud/discussions/120 on that topic.

Tested via the `emfcloud-modelserver-theia` example application:
- Send edit request for `Coffee.ecore` to set `ControlUnit` name to `ControlUnitNew`
- Send save request for `Coffee.ecore`
- Changes are not reflected
- Send `saveAll` request for `Coffee.ecore` persists the changes

Investigate if other requests are affected as well.

**Comment by eneufeld** [comment]
We should check whether this is by chance fixed with the v2 refactorings

**Comment by ndoschek** [comment]
This problem persists in combination with `emfcloud-modelserver-theia` using `v1`. Therefore an issue in the `emfcloud-modelserver-theia` repository was created: [emfcloud-modelserver-theia/issues/90](https://github.com/eclipse-emfcloud/emfcloud-modelserver-theia/issues/90).
The basic workflow without the Theia application works (e.g. via direct requests or if using the `ExampleModelServerClient`) on the Model Server under Windows. Therefore I close this issue in this repo.
